//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer_characteristics
    {
        public long id { get; set; }
        public Nullable<long> id_dispositivo { get; set; }
        public string ram { get; set; }
        public string rom { get; set; }
        public string codigo_cne { get; set; }
        public string nombre_dispositivo { get; set; }
        public string procesador { get; set; }
    }
}
