//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestion_activos
    {
        public long id { get; set; }
        public long id_equipo { get; set; }
        public string asignado_a { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public Nullable<long> id_departamento { get; set; }
        public string custodio { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual departamentos departamentos1 { get; set; }
        public virtual gestion_hardware gestion_hardware { get; set; }
    }
}
