//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestion_hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gestion_hardware()
        {
            this.control_activos = new HashSet<control_activos>();
            this.gestion_activos = new HashSet<gestion_activos>();
            this.historial_mantenimiento = new HashSet<historial_mantenimiento>();
            this.suministros_remanufacturados = new HashSet<suministros_remanufacturados>();
        }
    
        public long id { get; set; }
        public long id_equipo { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<System.DateTime> fecha_adquisicion { get; set; }
        public string estado { get; set; }
        public string ubicacion { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<control_activos> control_activos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gestion_activos> gestion_activos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_mantenimiento> historial_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suministros_remanufacturados> suministros_remanufacturados { get; set; }
    }
}
