//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_mantenimiento
    {
        public long id { get; set; }
        public long id_equipo { get; set; }
        public Nullable<System.DateTime> fecha_mantenimiento { get; set; }
        public string detalles { get; set; }
    
        public virtual gestion_hardware gestion_hardware { get; set; }
    }
}
