//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_custodios
    {
        public long id { get; set; }
        public Nullable<System.DateTime> timestamp_evento { get; set; }
        public string custodio { get; set; }
        public Nullable<long> id_departamento { get; set; }
    }
}
