//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConext : DbContext
    {
        public DbConext()
            : base("name=DbConext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<control_activos> control_activos { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<gestion_activos> gestion_activos { get; set; }
        public virtual DbSet<gestion_hardware> gestion_hardware { get; set; }
        public virtual DbSet<historial_custodios> historial_custodios { get; set; }
        public virtual DbSet<historial_mantenimiento> historial_mantenimiento { get; set; }
        public virtual DbSet<suministros_remanufacturados> suministros_remanufacturados { get; set; }
        public virtual DbSet<computer_characteristics> computer_characteristics { get; set; }
    }
}
