//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> borrado { get; set; }
        public string cargo { get; set; }
        public string email { get; set; }
        public string tempPass { get; set; }
    }
}
