//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class suministros_remanufacturados
    {
        public long id { get; set; }
        public string id_equipo { get; set; }
        public string tipo_suministro { get; set; }
        public Nullable<System.DateTime> fecha_retiro { get; set; }
        public string id_equipoAsignado { get; set; }
        public bool borrado { get; set; }
    
        public virtual gestion_hardware gestion_hardware { get; set; }
    }
}
